name: Deploy to cPanel

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: https://45.90.220.8
          username: root
          password: iRCg.@DaGXJF3P+RM7/w
          local-dir: ./
          server-dir: /var/lib/docker/volumes/b08sskowwos848kk8w4o84g0_wordpress-files/_data/wp-content/
